### ISSUE TITLE
cli: simplify configuration

### ISSUE THREAD

**Issue by diegodelemos** [inveniosoftware/docker-services-cli#15]
```console
$ docker-services-cli --version
docker-services-cli, version 0.2.1
```

## Describe the bug

If one misses setting for example the `SQLALCHEMY_DATABASE_URI`, the tests will just run using the default DB (which in the case of Invenio is SQLite [see docs](https://invenio-db.readthedocs.io/en/latest/configuration.html#SQLALCHEMY_DATABASE_URI)), e.g.:

```console
$ docker-services-cli up postgresql
$ pytest -m tests
$ # pytest/application will connect to the default DB
$ # test can pass but they are not run using postgresql
```

## Expected behavior

```console
$ export DB=MYSQL
$ docker-services-cli up
$ # injects the needed env variables, e.g. sqlalchemy connection string
$ env | grep SQLALCHEMY_DATABASE_URI
SQLALCHEMY_DATABASE_URI=<mysql-container-connection-string->
$ # run python tests, tests/app code read connection strings from environment 
$ docker-services-cli down
$ # cleans up environment
$ env | grep SQLALCHEMY_DATABASE_URI | wc -l
0
```

## Additional context

>Yep. Iit simplifies both GH Actions and running tests locally, so I would go ahead.

>It could also be:

>```
>export DB=MYSQL_5_LATEST
>docker-services-cli up
>```

>If you want the latest release:

>```
>export DB=MYSQL
>docker-services-cli up
>```

_Originally posted by @lnielsen in https://github.com/inveniosoftware/invenio-records/pull/239#discussion_r534083525_

**Comment by lnielsen** [comment]
Random comments from discussions:

```
{
      'postgresql': (postgresql, 12)
      'postgresql9': (postgresql, 9)
      'postgresql11': (postgresql, 11)
      'postgresql12': (postgresql, 12)
}

# Shell
env DB=postgresql9 ./run-tests.sh

# run-tests.sh
docker-services-cli up ${DB} ... 
--> export SQLALCHEMY_DATABASE_URI=...
docker-services-cli up --database=${DB}
